### ISSUE TITLE
发现一个问题待解决

### ISSUE THREAD

**Issue by slabbiu7** [eritpchy/aliyundrive-webdav#102]
想更改云盘账号，退出登录后，用新账号扫码登录，登录完成还是老账号的内容！
重复实验过多次，无法切换到新的账号。
这应该是一个BUG。

**Comment by sandaoyan** [comment]
长按清除数据，或者卸载重装

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
