### ISSUE TITLE
Bug/3.02版/文件夹日期一直不对

### ISSUE THREAD

**Issue by iduoe** [eritpchy/aliyundrive-webdav#111]
nplayer的列表中所有文件夹显示 
1970/01/01 
文件管理软件里，显示 N/A 
alist的显示就没问题。
![Screenshot_2023-03-04-21-28-17-49_79350d495578c0ed37372bf4f264524a](https://user-images.githubusercontent.com/117105738/222904505-9753d32e-c797-4861-a55c-9a5b8f6cb264.jpg)

![Screenshot_2023-03-04-21-28-32-42_79350d495578c0ed37372bf4f264524a](https://user-images.githubusercontent.com/117105738/222904510-a246c94f-ca7a-4238-83ff-5d01c25a8708.jpg)

**Comment by eritpchy** [comment]
![WechatIMG1508](https://user-images.githubusercontent.com/8630635/222906347-2a0d8fa8-0259-4167-8970-294c06378133.jpeg)
经测试 3.0.2 版本暂未发现此问题,  https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.2

**Comment by iduoe** [comment]
> ![WechatIMG1508](https://user-images.githubusercontent.com/8630635/222906347-2a0d8fa8-0259-4167-8970-294c06378133.jpeg) 经测试 3.0.2 版本暂未发现此问题, https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.2

文件没事，文件夹的日期不对。

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.3.0.3.release.apk.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10890810/net.xdow.webdavaliyundriver.3.0.3.release.apk.zip)
试试

**Comment by iduoe** [comment]
3.03
Reex和文件管理里日期显示都没问题了。
唯独nplayer还是1970年，很诡异。
总体不影响使用，谢谢作者的付出。
![Screenshot_2023-03-05-17-19-20-42_27a7952b6b1c29b2b4b5cd929ddd3b40.jpg](https://user-images.githubusercontent.com/117105738/222952427-0e611f33-6625-4526-8342-46d26c4806ca.jpg)

![Screenshot_2023-03-05-17-23-46-29_79350d495578c0ed37372bf4f264524a.jpg](https://user-images.githubusercontent.com/117105738/222952438-533f052f-c588-47b8-ace9-0fe84b1d2087.jpg)

**Comment by eritpchy** [comment]
我找了半天下的nplayer文件夹都没有日期显示。。

**Comment by iduoe** [comment]
根目录没有日期，子目录日期不对。但是alist的根目录是有正确日期的。

**Comment by iduoe** [comment]
还有一个细节，每次刷新子目录，日期是动的。初始好像是8点整。每次刷新会增加刚刚流逝的几秒。

**Comment by iduoe** [comment]
![Screenshot_2023-03-05-19-46-31-89_79350d495578c0ed37372bf4f264524a.jpg](https://user-images.githubusercontent.com/117105738/222958534-ec108a00-9925-43d7-b244-c417f9d55741.jpg)
