### ISSUE TITLE
新版在按了停止之后会卡住界面

### ISSUE THREAD

**Issue by lv65-max** [eritpchy/aliyundrive-webdav#112]
在停止视频画面关闭后会卡住，按什么键也不管用，要等大概三两分钟才可以。不知道有没有遇到的，使用的是海美迪盒子。

**Comment by lv65-max** [comment]
> 什么播放器

kodi

**Comment by lv65-max** [comment]
> > 什么播放器
> 
> 最新版kodi

用了一下nplayer没问题

**Comment by eritpchy** [comment]
更新[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)试试
