### ISSUE TITLE
登录之后有的目录无法通过webdav访问

### ISSUE THREAD

**Issue by lyinglu** [eritpchy/aliyundrive-webdav#115]
网盘有几个放电影的目录，其中一个目录使用webdav方式无法访问（其余目录无异常）。访问程序为：nplayer、kodi。

另，bubbleupnp程序无法通过webdav形式挂载。

**Comment by lyinglu** [comment]
![Screenshot_20230307-144250](https://user-images.githubusercontent.com/72125266/223343752-15dbb51c-2f7a-4dc1-8783-d564bdeea641.png)

**Comment by lyinglu** [comment]
![Screenshot_20230307-144435](https://user-images.githubusercontent.com/72125266/223344485-a1bec4ea-57d1-45d3-b0a0-759b7a98e301.png)
![Screenshot_20230307-144440](https://user-images.githubusercontent.com/72125266/223344568-dfd176dc-8be4-4d2b-aed5-b42e81367286.png)

**Comment by lyinglu** [comment]
![Uploading Screenshot_20230307-150322.png…]()

**Comment by lyinglu** [comment]
![Screenshot_20230307-150322](https://user-images.githubusercontent.com/72125266/223348827-f5506d3a-582b-487d-b350-eacecfe9df9f.png)

**Comment by eritpchy** [comment]
目录分享给我

**Comment by eritpchy** [comment]
暂时无法重现

**Comment by lyinglu** [comment]
电锯惊魂1-9部 全系列 全高清 BD1080P
https://www.aliyundrive.com/s/26sQgWec6p9
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

由于空间溢出，只能放在其他目录下，抱歉。这个无法打开的目录就是这个链接

**Comment by lyinglu** [comment]
文件名字的书名号影响的。

**Comment by eritpchy** [comment]
经测试 https://github.com/eritpchy/webdav-aliyundriver-android/issues/94和这个是同一个问题

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.3.0.4.release.apk.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10908838/net.xdow.webdavaliyundriver.3.0.4.release.apk.zip)
试试

**Comment by lyinglu** [comment]
非常抱歉，文件名称我已经改了，目前无法验证。
