### ISSUE TITLE
3.0.2版本部分目录无法访问

### ISSUE THREAD

**Issue by qwer2069859** [eritpchy/aliyundrive-webdav#117]
使用的是手机挂载，然后电视KODI19.4播放，云盘下只有2个文件夹，一个电影一个电视剧，电视剧文件夹可正常打开播放，电影文件夹kodi转一圈就没了，打不开，kodi上也没有任何提示，手机上现在隐藏了日志看不了，求解决

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/files/10908838/net.xdow.webdavaliyundriver.3.0.4.release.apk.zip
试试
