### ISSUE TITLE
传输卡顿，好像被限速

### ISSUE THREAD

**Issue by Sunnycookie** [eritpchy/aliyundrive-webdav#119]
阿里网盘会限速吗，还是webdav的问题？
一开始正常播放，突然发生卡顿，再就一直卡缓冲，卡顿播放时速度显示最高355k/s

**Comment by Sunnycookie** [comment]
破案，阿里网盘限速了，pc直接用阿里客户端下载都限速。

**Comment by eritpchy** [comment]
水管流量是有限的
