### ISSUE TITLE
急！在安卓电视上安装3.0.8 开启失败

### ISSUE THREAD

**Issue by Nemolovesclaire** [eritpchy/aliyundrive-webdav#122]
n1 媒体盒，安卓 7.1.2
日志显示：failed org.eclipse.jetty.server.Server@8d7c3c4:java.net.bindexception:address already in use
![image](https://user-images.githubusercontent.com/125125277/231013538-26442fc6-efda-4705-b63a-6b36aeae1cf4.jpg)

**Comment by eritpchy** [comment]
换个端口
