### ISSUE TITLE
求助：小米电视没有电源优化设置，怎么守护webdav不被杀进程

### ISSUE THREAD

**Issue by zach7788** [eritpchy/aliyundrive-webdav#125]
如题
有没有用小米电视的朋友跟我遇到一样的烦恼？
我在小米电视ES PRO 65寸上死活找不到电源优化权限的设置，导致webdav服务只要进后台就会被杀掉而无法使用。
求大神指教，有没有解决方案？？

**Comment by eritpchy** [comment]
有条件就用nas或者电脑挂哦

**Comment by zach7788** [comment]
> 

这次是帮朋友弄的，他是肯定没这个条件~~~
现在逼的没办法，在他的华为平板里面装了一个。。。
但是还是希望能在小米电视上后台挂
有没有办法啊，大佬

**Comment by zach7788** [comment]
> 有条件就用nas或者电脑挂哦

这次是帮朋友弄的，他是肯定没这个条件~~~
现在逼的没办法，在他的华为平板里面装了一个。。。
但是还是希望能在小米电视上后台挂
有没有办法啊，大佬

**Comment by eritpchy** [comment]
目前不行, 建议使用其他解决方案

**Comment by zach7788** [comment]
> 目前不行, 建议使用其他解决方案

好吧。。。。
期待后面能有转机~~~~~
谢谢了

**Comment by 1Xiaoxiaoqiang111** [comment]
tcl电视同样问题，也只能装华为平板上，找了很久没看到解决方法

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
