### ISSUE TITLE
kodi挂载后无法播放

### ISSUE THREAD

**Issue by Ejoyyee** [eritpchy/aliyundrive-webdav#128]
能看到文件，点击播放就说一个或者多个项目播放失败。是我什么设置有问题还是阿里云盘限制了，阿里云盘webdev目前是能正常使用的吗？

**Comment by Ejoyyee** [comment]
自己找到原因了，是裴讯k2p作为2级路由，开了dhcp，多套了一层ip，把网线接到lan口，关闭dhcp以后，用主路由的ip段就没问题了

**Comment by eritpchy** [comment]
ok
