### ISSUE TITLE
无法使用SwiftBackup进行备份

### ISSUE THREAD

**Issue by KongNan** [eritpchy/aliyundrive-webdav#13]
默认安装启动，浏览器访问http 8080可以看到文件列表。但使用swiftBackup添加WebDAV时使用同样参数就无法连接

**Comment by maxfun0** [comment]
没这个问题

**Comment by infoma990** [comment]
楼主解决了吗？现在不卸载重新安装，刷机都试过了，浏览器能看到目录，但是es浏览器，mix浏览器，splayer都无法挂载，刷新不出来文件。

**Comment by eritpchy** [comment]
old
