### ISSUE TITLE
一个未知的暂停原因

### ISSUE THREAD

**Issue by WuYang09661** [eritpchy/aliyundrive-webdav#130]
观看视频时没两三分钟左右就会卡住，必须切回app再切回视频软件，两分钟后又卡住了 webdav版本是最新的，播放器是nplayer1.777（如果加密app小窗挂在前台就没事，但是这样会挡住屏幕）系统是realmeui4.0（魔改color）安卓13

**Comment by WuYang09661** [comment]
查看了系统日志，一切正常

**Comment by eritpchy** [comment]
部分系统无法常驻后台或存在后台控流限速(比如小米), 建议使用其他设备长期挂载, 比如群晖 树莓派,电脑, linux盒子等等

**Comment by Caligari999** [comment]
我家电视也是这样，以前都没问题，这次阿里更新完就开始出现问题了感觉

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
