### ISSUE TITLE
macos系统无法上传文件

### ISSUE THREAD

**Issue by drtk712** [eritpchy/aliyundrive-webdav#131]
macos系统无法上传文件
系统版本12.3.1
<img width="954" alt="image" src="https://github.com/eritpchy/aliyundrive-webdav/assets/48203587/1bc5d1ea-c3bf-42f7-b0f4-1e9966603aed">

**Comment by eritpchy** [comment]
下载3.3.0版本

**Comment by drtk712** [comment]
更新到3.3.0版本后解决
