### ISSUE TITLE
kodi挂载webdav问题

### ISSUE THREAD

**Issue by 5201313sky** [eritpchy/aliyundrive-webdav#132]
电视是SONY的，前天开始看不了，webdav是3.1.0 ，KODI是20，以前看都可以的，现在打开就显示远程共享，路径未找到或无效，望解答！！！

**Comment by eritpchy** [comment]
什么设备开的webdav

**Comment by 5201313sky** [comment]
> 



> 文学史

你好，是索尼X91K

**Comment by eritpchy** [comment]
后台掉了

**Comment by 5201313sky** [comment]
> 后台掉了

哦，好的，我试试

**Comment by 5201313sky** [comment]
> > 后台掉了
> 
> 哦，好的，我试试

已解决了，我两个软件删除，再重新安装，重新配置过，就可以了
