### ISSUE TITLE
如何编译成apk

### ISSUE THREAD

**Issue by xiaodatao2007** [eritpchy/aliyundrive-webdav#133]
1、如何才能编译成apk，像你release.apk
https://github.com/eritpchy/aliyundrive-webdav/releases/download/3.1.0/net.xdow.webdavaliyundriver.3.1.0.release.apk

2、是不是这个不开源？

**Comment by eritpchy** [comment]
是的UI不开源

**Comment by xiaodatao2007** [comment]
好的
