### ISSUE TITLE
用nplayer点击挂载的webdav出现（status503）503

### ISSUE THREAD

**Issue by lsir888** [eritpchy/aliyundrive-webdav#139]
网页打开ip:8080出现下面这些（部分页面）：
HTTP ERROR 503
Problem accessing /. Reason:

    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Caused by:
org.eclipse.jetty.servlet.ServletHolder$1: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:428)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:474)

**Comment by eritpchy** [comment]
有没有更多的日志

**Comment by lsir888** [comment]
> 有没有更多的日志

更多的日志 和上面的一样都是重复，在nplayer和kodi中都不能读出列表，出现（status503）503。但是如果换一个阿里云盘的账号就能挂载，用的手机安卓版本。并且用win7版本的话原账号也没事。估计和原来试用4T空间后装满东西再没续费有关，但测试充值后也是一样没变化。

**Comment by eritpchy** [comment]
显示内部日志钩上, 程序不要切后台用浏览器打开,看看有没有更多日志

**Comment by lsir888** [comment]
> 显示内部日志钩上, 程序不要切后台用浏览器打开,看看有没有更多日志

非常感谢回复，经过回退到3.0.8版本后不断的查找原因，最终发现应该和手机严重杀后台有关。

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
