### ISSUE TITLE
3.1版本服务启动失败

### ISSUE THREAD

**Issue by sallusxavier** [eritpchy/aliyundrive-webdav#140]
前几个月一直能用，刚刚点进去如图所示报错了。
我试过重新扫码，卸载又下载重装apk，还是报错

![Screenshot_2023_1013_172306](https://github.com/eritpchy/aliyundrive-webdav/assets/61200021/efa72a4c-b0a3-4ae4-827f-761f0ed2ded9)

**Comment by eritpchy** [comment]
端口号换个数字

**Comment by sallusxavier** [comment]
感谢，解决了！
