### ISSUE TITLE
默认挂载的是备份盘，希望提供访问资源盘的功能

### ISSUE THREAD

**Issue by bluoy** [eritpchy/aliyundrive-webdav#142]
阿里云盘目前将空间划分成了备份盘和资源盘，缺省访问的是备份盘。希望可以提供俩个空间的切换功能。

**Comment by eritpchy** [comment]
收到

**Comment by WuYang09661** [comment]
现在能访问资源盘了吗

**Comment by WoodwindHu** [comment]
同求这个功能

**Comment by michsun7** [comment]
不知道几时再更新这个功能

**Comment by eritpchy** [comment]
<img width="167" alt="image" src="https://github.com/eritpchy/aliyundrive-webdav/assets/8630635/5ad6d247-c3cc-4672-aa88-a8f9bd8059af">

**Comment by michsun7** [comment]
求更新

**Comment by eritpchy** [comment]
除了安卓端 其他客户端已经更新了

**Comment by michsun7** [comment]
唯独更需要安卓版

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
