### ISSUE TITLE
索尼电视65X90J从3.1.0更新到3.1.1后启动一直卡在白屏

### ISSUE THREAD

**Issue by cashrmb** [eritpchy/aliyundrive-webdav#143]
电视上在线更新中途弹出去断了两次，在更新完毕打开白屏，不管是杀进程，关电源，u盘重新安装皆是如此，QQ群5个都满，只好这里请教了

**Comment by eritpchy** [comment]
安卓几

**Comment by 934556826** [comment]
我也是相同的更新后白屏问题，索尼电视65X90K，Android TV 操作系统
楼主的X90J是安卓10

**Comment by eritpchy** [comment]
方便录个屏吗

**Comment by 934556826** [comment]
打开白屏，什么内容都没显示，也没有报错弹框

**Comment by eritpchy** [comment]
有adb权限吗

**Comment by cashrmb** [comment]
没有开启过adb权限，之前都没问题，这次很奇怪

**Comment by eritpchy** [comment]
能开就给我远程连电脑调试一下

**Comment by minmin9846** [comment]
我也经历同样的问题...白屏

**Comment by minmin9846** [comment]
我的电视型号是sony 85X90K 3.1.0更新到3.1.1进入时一直白屏 无法进行任何操作

**Comment by cashrmb** [comment]
> 能开就给我远程连电脑调试一下

不知道怎么开，明天试一下只能

**Comment by eritpchy** [comment]
试试, 解压缩后安装
[net.xdow.webdavaliyundriver.3.1.2.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13441315/net.xdow.webdavaliyundriver.3.1.2.release.apk.zip)

**Comment by cashrmb** [comment]
> 试试, 解压缩后安装 [net.xdow.webdavaliyundriver.3.1.2.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13441315/net.xdow.webdavaliyundriver.3.1.2.release.apk.zip)

好的，明天安装一下试试

**Comment by cashrmb** [comment]
> 试试, 解压缩后安装 [net.xdow.webdavaliyundriver.3.1.2.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13441315/net.xdow.webdavaliyundriver.3.1.2.release.apk.zip)
大侠，我这里依然是白屏，和之前3.1.1一样的效果

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.3.1.3.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445734/net.xdow.webdavaliyundriver.3.1.3.release.apk.zip)
再试试, 解压缩后安装

**Comment by cashrmb** [comment]
> [net.xdow.webdavaliyundriver.3.1.3.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445734/net.xdow.webdavaliyundriver.3.1.3.release.apk.zip) 再试试, 解压缩后安装

这次可以了。冒昧的问问这程序怎么还越做越小了，是去掉了很多东西吗？另外个人觉得登录默认为扫二维码好点，毕竟电视登录输入密码比较费劲，那个登录二维码的小图标要不注意还真没看到哈

**Comment by cashrmb** [comment]
> [net.xdow.webdavaliyundriver.3.1.3.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445734/net.xdow.webdavaliyundriver.3.1.3.release.apk.zip) 再试试, 解压缩后安装

辛苦了大侠，等待你的多功能新版本

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.3.1.5.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445850/net.xdow.webdavaliyundriver.3.1.5.release.apk.zip)
[net.xdow.webdavaliyundriver.3.1.4.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445851/net.xdow.webdavaliyundriver.3.1.4.release.apk.zip)
二维码后续会做优化, 还得麻烦你分别测一下这两个版本

**Comment by cashrmb** [comment]
> [net.xdow.webdavaliyundriver.3.1.5.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445850/net.xdow.webdavaliyundriver.3.1.5.release.apk.zip)
> 
> [net.xdow.webdavaliyundriver.3.1.4.release.apk.zip](https://github.com/eritpchy/aliyundrive-webdav/files/13445851/net.xdow.webdavaliyundriver.3.1.4.release.apk.zip)
> 
> 二维码后续会做优化, 还得麻烦你分别测一下这两个版本

不麻烦，这两个版本都没有问题，我看点击去电源优化管理也可以到设置界面

**Comment by eritpchy** [comment]
ok 了解了, 感谢

**Comment by cashrmb** [comment]
大侠客气了，还得感谢你开发这么好用的程序

**Comment by Magic-33** [comment]
请问索尼电视如何能不杀后台？85x90L，安卓10

**Comment by cashrmb** [comment]
> 请问索尼电视如何能不杀后台？85x90L，安卓10

找设置-应用-特殊应用权限-电源优化，把这个APP的优化关上，就不杀后台了

**Comment by wangsm00123** [comment]
> > 请问索尼电视如何能不杀后台？85x90L，安卓10
> 
> 找设置-应用-特殊应用权限-电源优化，把这个APP的优化关上，就不杀后台了

为什么我每次开电视都要设置一次电源优化，好麻烦，有没有一劳永逸的方法？

**Comment by Magic-33** [comment]
> > 请问索尼电视怎么样不杀后台？85x90L，安卓10> > 请问索尼电视怎么样不杀后台？85x90L，安卓10>> 找设置-应用-特殊应用权限-电源优化，把这个APP的优化关上，就不杀后台了>> 找设置-应用-特殊应用权限-电源优化，把这个APP的优化关上，就不杀后台了 
z

**Comment by Magic-33** [comment]
> > 请问索尼电视如何能不杀后台？85x90L，安卓10
> 
> 找设置-应用-特殊应用权限-电源优化，把这个APP的优化关上，就不杀后台了

谢谢！搞定了
