### ISSUE TITLE
手机老是掉后台解决办法，

### ISSUE THREAD

**Issue by 9674454** [eritpchy/aliyundrive-webdav#145]
所有能root手机都适用，直接把web转换成系统应用就行，其实给安卓上加个通知栏保活啥的应该就适用所有手机了。希望大佬能考虑一下

**Comment by 9674454** [comment]
实用就行，李跳跳就是无障碍＋通知栏，开机用到关机都不掉

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
