### ISSUE TITLE
关于直连模式

### ISSUE THREAD

**Issue by iwestlin** [eritpchy/aliyundrive-webdav#146]
我
- 在iPad上用最新版的nplayer
- 在mac上用finder
- 在安卓上用es文件浏览器
连接本程序(linux 3.1.1版本)在服务器上启动的WebDAV服务，在播放视频时观察到流量依旧是经过服务器的（流量跑满服务器上行带宽）
即使我指定了`--aliyundrive.download-proxy-mode=Direct`参数，依然如此，请问是什么原因？

**Comment by eritpchy** [comment]
<img width="619" alt="image" src="https://github.com/eritpchy/aliyundrive-webdav/assets/8630635/a640c698-db54-4372-bfc9-faed4d51b898">

**Comment by iwestlin** [comment]
谢了，我当时下的时候还没有发布3.4.2的二进制  https://file.xdow.net/aliyundriver/3.4.2
