### ISSUE TITLE
卡在这个界面

### ISSUE THREAD

**Issue by Shimmer2** [eritpchy/aliyundrive-webdav#148]
[
![IMG_5231](https://github.com/eritpchy/aliyundrive-webdav/assets/79088619/0dc7d58e-f7c2-4fa5-bab3-55e2769bb90e)

**Comment by eritpchy** [comment]
网不好 多试试

**Comment by eritpchy** [comment]
内核包已上传 https://file.xdow.net/aliyundriver/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E6%A0%B8%E5%8C%85
手动安装即可

**Comment by Shimmer2** [comment]
刚刚是网络问题，现在已经解决了，非常感谢！！

**Comment by Shimmer2** [comment]
我在电视上使用的，遥控器操作网盘界面有时候不知道光标跑去哪了，不知能否优化一下电视端遥控器的操作？谢谢！！

**Comment by eritpchy** [comment]
是有优化的, 方向键随便多按几次!
后续版本会进一步优化!

**Comment by Shimmer2** [comment]
非常感谢你！软件里的更新好像用不了，点了没反应，只能来这里下载安装包

**Comment by eritpchy** [comment]
旧版本(<4.0.0) 版本未使用镜像链接更新, 用的是github服务, 会因网络因素无法升级, 这个已经在4.0.0版本优化了

**Comment by Shimmer2** [comment]
太好了！另外想问一下，我准备在电视盒子上安装coreelec系统，但是那个系统好像不能安装安卓软件，只能安装插件，请问有打算做一个kodi的插件吗？

**Comment by eritpchy** [comment]
coreelec 支持 docker 你直接用docker版就行了

**Comment by Shimmer2** [comment]
好的，谢谢你！！
