### ISSUE TITLE
HK1 Box盒子安装最新版打开报错

### ISSUE THREAD

**Issue by Shimmer2** [eritpchy/aliyundrive-webdav#150]
![Uploading IMG_5238.jpeg…]()

**Comment by Shimmer2** [comment]
1. 
![IMG_5238](https://github.com/eritpchy/aliyundrive-webdav/assets/79088619/b79396f8-7f14-4e2c-9c57-721fcaf6a6c5)

**Comment by eritpchy** [comment]
系统时间不对
