### ISSUE TITLE
更新最新版本以后kodi无法挂载阿里云盘了

### ISSUE THREAD

**Issue by shark-8615** [eritpchy/aliyundrive-webdav#156]
更新以后 挂载地址    “  4.0.0及以上版本 webdav连接地址已改为 http://{ip}:{端口}/dav  ”

但是kodi设置中端口后面无法输入/dav ，kodi 固定几行格式中 ，端口只能输入数字 ，输入完以后自动生成地址。

原来的webdav地址没改能直接挂载 ，现在挂载不了拉 。

请问开发者 ，webdav地址能否还原啊 。

**Comment by eritpchy** [comment]
<img width="720" alt="37298109bb7aa26e533df1e9f2d75001" src="https://github.com/eritpchy/aliyundrive-webdav/assets/8630635/b2740543-4cf2-4f1d-adfa-8f40e5a08718">

**Comment by shark-8615** [comment]
搞定了，谢谢大佬的支持！
