### ISSUE TITLE
有知道小米电视如何设置省电配置常驻内存不被kill的吗

### ISSUE THREAD

**Issue by netear** [eritpchy/aliyundrive-webdav#34]
切换到播放软件后没几分钟就服务终止了

**Comment by zksd2022** [comment]
下载一个当贝桌面，进去后里面有特殊权限管理，把阿里webdav的省电取消即可

**Comment by chijiu** [comment]
> 下载一个当贝桌面，进去后里面有特殊权限管理，把阿里webdav的省电取消即可

兄弟，当贝桌面哪个位置有特殊权限管理，我怎么没找到呀

**Comment by zksd2022** [comment]
安装当贝桌面：
进入当贝桌面-遥控器按上-设置-系统设置-应用-特殊应用权限-电源优化-关闭阿里云盘webdav优化-退出当贝桌面即可

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
