### ISSUE TITLE
1.8还是用不了

### ISSUE THREAD

**Issue by gehene** [eritpchy/aliyundrive-webdav#67]
浏览器输入ip➕端口可以打开,但是用reex添加就是失败
![IMG_20230114_035918](https://user-images.githubusercontent.com/122592269/212409306-1dd49e9d-e491-4787-829c-a6f74f01cb70.jpg)
![Screenshot_2023-01-14-03-58-49-01_5347002c35ab2cbd17675ead7121ce1c](https://user-images.githubusercontent.com/122592269/212409314-70acc227-bc9f-4122-acae-758efcfccbf3.jpg)
![Screenshot_2023-01-14-03-59-28-64_5347002c35ab2cbd17675ead7121ce1c](https://user-images.githubusercontent.com/122592269/212409318-cbb9a644-3e73-403c-bfdb-a2532cc9db87.jpg)

**Comment by beijinggala** [comment]
一样的问题

**Comment by gehene** [comment]
> 一样的问题

文件夹的名称不能带/

**Comment by eritpchy** [comment]
old
