### ISSUE TITLE
如果能支持HTTPS，就能用上FolderSync，这样实用性和可玩性立刻就大大提高了。

### ISSUE THREAD

**Issue by YeXiongNan** [eritpchy/aliyundrive-webdav#74]
如果能支持HTTPS，就能用上FolderSync，这样实用性和可玩性立刻就大大提高了。

**Comment by wenhelinlu** [comment]
特别期待能上https

**Comment by eritpchy** [comment]
FolderSync 能认自签名https吗, 估计不行, 那你想用上还是挺麻烦的, 还得准备自己的域名....或者root

**Comment by YeXiongNan** [comment]
> FolderSync 能认自签名https吗, 估计不行, 那你想用上还是挺麻烦的, 还得准备自己的域名....或者root

允许自签名，软件里有明确的选项。
如果可以用FolderSync，就可以把手机里面的任何文件与阿里云自动即时同步，甚至是网盘与网盘之间自动同步，多好呀

**Comment by wenhelinlu** [comment]
虽然AutoSync可以连接HTTP协议的WebDAV，但是感觉还是不如FolderSync好用，所以还是特别期待能支持HTTPS。

**Comment by eritpchy** [comment]
已支持Https, 请测试
[net.xdow.webdavaliyundriver.2.0.5.release.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10779411/net.xdow.webdavaliyundriver.2.0.5.release.zip)

**Comment by wenhelinlu** [comment]
> 已支持Https, 请测试 [net.xdow.webdavaliyundriver.2.0.5.release.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10779411/net.xdow.webdavaliyundriver.2.0.5.release.zip)

经测试启用Https后，FolderSync可以连接，但是本软件经常会提示“无响应”。

**Comment by eritpchy** [comment]
??,什么设备？安卓版本是多少有条件抓一下adb logcat

**Comment by wenhelinlu** [comment]
> ??,什么设备？安卓版本是多少有条件抓一下adb logcat

环境是小米11，MIUI14（Android 13）。不知道是不是因为云盘的一级目录有以前误传的几十张照片导致的，因为我看app界面上显示的日志里有照片的详细信息，比如地理位置、时间等等，我把照片删了，只保留几个一级目录，刚刚又试了一下FolderSync同步，没有再报错。能否增加一个主界面日志显示的开关？感觉当大量日志显示的时候应用容易FC。等下次再出现无响应的时候，我抓一下log。

**Comment by YeXiongNan** [comment]
> 已支持Https, 请测试 [net.xdow.webdavaliyundriver.2.0.5.release.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10779411/net.xdow.webdavaliyundriver.2.0.5.release.zip)

各种情况单向双向等等都试了一遍，成功！正在兴奋中，上传下载同步都很快，辛苦了，感谢感谢，开心！………………………………………刚开始的时候有一个文件总是出错，下载失败，FolderSync提示“文件大小错误”，还以为出什么问题了，抓狂，好不容易找到了那个文件，才发现，原来有一张图片竟然被阿里云和谐了，无法访问了，嗯，你懂的，删掉就一切正常了。

**Comment by eritpchy** [comment]
> > ??,什么设备？安卓版本是多少有条件抓一下adb logcat
> 
> 环境是小米11，MIUI14（Android 13）。不知道是不是因为云盘的一级目录有以前误传的几十张照片导致的，因为我看app界面上显示的日志里有照片的详细信息，比如地理位置、时间等等，我把照片删了，只保留几个一级目录，刚刚又试了一下FolderSync同步，没有再报错。能否增加一个主界面日志显示的开关？感觉当大量日志显示的时候应用容易FC。等下次再出现无响应的时候，我抓一下log。

嗯, 如果是大量日志就不用抓了, 我知道怎么回事了(人懒)

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/issues/92#issuecomment-1438253407
先用着

**Comment by JUST-INTJ** [comment]
FolderSync 配置下面有一个小小的按钮。`允许不全安的连接` 。点上就能用http了。不容易发现。之前我也被折磨了很久，连不上还没有一点提示 以为是bug下了无数老个版本。

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)

**Comment by wenhelinlu** [comment]
> FolderSync 配置下面有一个小小的按钮。`允许不全安的连接` 。点上就能用http了。不容易发现。之前我也被折磨了很久，连不上还没有一点提示 以为是bug下了无数老个版本。

没找到这个按钮啊。。。

**Comment by wenhelinlu** [comment]
> [4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)

4.0改成http，FolderSync又没法用了🤣

**Comment by wenhelinlu** [comment]
> [4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)

请问“使用https”这个选项无效了吗？

**Comment by wenhelinlu** [comment]
> [4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)

用这个版本，开启`使用https`后，在FolderSync的WebDAV配置中测试成功，但是实际同步时失败，报
>
>错误
>501:Method PROPFIND is not defined in RFC 2068 and is not supported by the Servlet API...”
