### ISSUE TITLE
swift backup选择webdav云备份覆盖的时候报错，我查日志是因为重命名的时候存在同名文件

### ISSUE THREAD

**Issue by wch352136** [eritpchy/aliyundrive-webdav#75]
1.swift backup是一款手机备份app，可以备份到本地或者云端，其中云端支持webdav的方式
2.通过大佬的项目我把阿里云挂载到手机上了
3..swift backup也正确识别并且上传了第一版备份，完全没问题
4.但是过几天做增量备份的时候，却发现swiftbackup总报错，如下图
![image](https://user-images.githubusercontent.com/17609338/218307716-0690ed85-81f7-4799-96d8-dd4a3d9ce661.png)
5.然后查大佬app的日志发现好像是覆盖备份的时候，最后一步重命名，报错了，原因是因为目标名字已经存在了，所以直接整个往回滚了
![image](https://user-images.githubusercontent.com/17609338/218307817-23a973e9-f1e0-4327-82eb-250344407256.png)

然而我用其他的云盘，如谷歌，onedrive啥的却没有问题（不过他们太慢了），所以想看看有没有解决办法

**Comment by eritpchy** [comment]
官方的这个api表现很奇怪, 还得继续折腾

**Comment by eritpchy** [comment]
盲猜是我上次报bug他们后来改了, 你不会想知道上次我调这个api..改名后可以出现两个相同的文件名

**Comment by eritpchy** [comment]
old
