### ISSUE TITLE
电视kodi 可以浏览网盘 但是打不开

### ISSUE THREAD

**Issue by roby411** [eritpchy/aliyundrive-webdav#84]
一打开就显示一个或多个项目播放失败
![Uploading C79B0E5C-995D-480E-BC75-436B68E63095.jpeg…]()

**Comment by roby411** [comment]
明明刚刚更新完还好用 过了一会就打不开了

**Comment by shinemoo** [comment]
我也一样，刚才电视上打开webdav更新到2.0，进kodi随便点开一个确认是可以看了。然后电视也没关就过了一会，想看就提示一个或多个项目播放失败

**Comment by roby411** [comment]
20:43:33 n*.s* w*.m*.DoGet /电视剧/重启人生/【幻月压制】（23年日剧】[重
启人生】[0611080P】1官方中字】.mp4 doBody causes Exception!
net.sf.webdav.exceptions.WebdavException：请求失败：/file/
get_download_url at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYun
DriverClient.java:177)
at com.github.zxbu.webdavteambition.store.AliYunDriverClientService.down
bad(AliYunDriverClientService.java:336)
at com.github.zxbu.webdavteambition.store.AliYunDriverFileSystemStore.g
etResourceContent(AliYunDriverFileSystemStore.java:93)
at net.sf.webdav.methods.DoGet.doBody(DoGet.java:68)
at net.sf.webdav.methods.DoHead.execute(DoHead.java: 155)
at net.sf.webdav.WebDavServletBean.e(WebDavServletBean.java:134)
at javax.servlet.http.HttpServlet.service(Unknown Source:4)
at org.eclipse.jetty.servlet.ServletHolder.handle(Unknown Source:64)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(SourceFile:
4) at
com.github.zxbu.webdavteambition.filter.ErrorFilter.doFilter(ErrorFilter.ja va:50)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(SourceFile:
2) at org.eclipse.jetty.servlet. ServletHandler.doHandle(Unknown Source:
105)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(Unknown
Source:8)
at org.eclipse.jetty.security.SecurityHandler.handle(SourceFile:2)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(Unknown
Source:26)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(Unknown
Source:108)
at org.eclipse.jetty.servlet.ServletHandler.doScope(Unknown Source:
201)
Lia bandler doScope(Unknown

**Comment by naihe138** [comment]
我的重启webdav 重新进kodi，是可以的

**Comment by roby411** [comment]
> 我的重启webdav 重新进kodi，是可以的

不好用啊 重启好几遍了

**Comment by eritpchy** [comment]
试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

**Comment by roby411** [comment]
> 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

已解决 感谢感谢

**Comment by shinemoo** [comment]
> 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

更新2.0.1了，暂时能放的起来，我去洗个澡回来再看看能不能放

**Comment by roby411** [comment]
> 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

还是不行 看完一个视频后 再打开别的视频 又还是和之前一样出现那个提示 打不开。。

**Comment by cjxyc** [comment]
还是不行，看几十分钟就看不了了，需要重新启动阿里webdav才可以看

**Comment by shinemoo** [comment]
> 还是不行，看几十分钟就看不了了，需要重新启动阿里webdav才可以看

+1
2.0.0的时候，我是退出kodi和webdav，再重启也不行
升到2.0.1以后，刚开始能看，看了一会想换个电视看，又出现“一打开就显示一个或多个项目播放失败”。然后我就有退出重启，不过这次重启以后又能看了

**Comment by eritpchy** [comment]
2.0.2 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.2

**Comment by JackWu725** [comment]
> 2.0.2 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.2

现在更新到了2.0.2，kodi找不到路径。内部日志显示云盘登陆设备过多，但是实际只登陆了一台。请问怎么解决？

**Comment by eritpchy** [comment]
> > 2.0.2 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.2
> 
> 现在更新到了2.0.2，kodi找不到路径。内部日志显示云盘登陆设备过多，但是实际只登陆了一台。请问怎么解决？

进设备管理器踢掉多余设备

**Comment by eritpchy** [comment]
试试 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4

**Comment by eritpchy** [comment]
old
