### ISSUE TITLE
电视盒子，安卓7.1系统。kodi挂载当初的1.70版本没问题，从1.80开始就再也没有成功过。

### ISSUE THREAD

**Issue by cuckookcuc** [eritpchy/aliyundrive-webdav#88]

**Comment by Borome1314** [comment]
是呀，用的海美迪，1.7很正常，之后就再也用不起来，最新的2.2也一样，kodi、dplay都连不上，目前只姨用当贝播放器，那画质还是比不了kodi

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4 试试

**Comment by Borome1314** [comment]
> https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4 试试

大佬，还是不行，能正常运行，电脑端也能正常访问浏览列表，但kodi和dplay都不行，dpaly不报错，但进去是空白，没有列表，kodi直接提示连接不上
![6](https://user-images.githubusercontent.com/122707608/220221983-487f4576-37f6-4daa-a492-92c0787fcb39.jpg)
![5](https://user-images.githubusercontent.com/122707608/220221987-7ccccc82-ed6d-4111-a746-1d6537f8adcb.jpg)
![4](https://user-images.githubusercontent.com/122707608/220221989-4227f660-d5a5-4b99-9462-60327008d443.jpg)
![3](https://user-images.githubusercontent.com/122707608/220221992-a777f813-edc9-423c-85cc-7afd57fd4cf5.jpg)
![2](https://user-images.githubusercontent.com/122707608/220221994-7ab5d6d2-9784-4fd6-ab7a-06fbd16b1460.jpg)
![1](https://user-images.githubusercontent.com/122707608/220221999-354225c2-d1d6-4b54-8cff-a8394ccea38a.jpg)

**Comment by eritpchy** [comment]
old
