### ISSUE TITLE
目录加载有问题

### ISSUE THREAD

**Issue by crirrm** [eritpchy/aliyundrive-webdav#90]
文件名长，包含字某些字符可能导致无法加载

**Comment by eritpchy** [comment]
举个例子

**Comment by eritpchy** [comment]
@vxbmtu94516 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4修复了

**Comment by crirrm** [comment]
> 举个例子
当存在如＂EVA/新世纪福音战士＂这个文件夹，包含此文件夹的目录将不会显示，表现为空白无法查看

**Comment by crirrm** [comment]
> 举个例子

但是具体的存在哪些字符不太清楚，需要重命名或者删除文件才能解决

**Comment by gehene** [comment]
> > 举个例子
> > 当存在如“EVA/新世纪福音战士”这个文件夹，包含这个文件夹的目录不会显示，表现为空白无法查看
> > ![截图_2023-02-20-21-03-05-764_com 阿里云databox](https://user-images.githubusercontent.com/84889012/220118609-ca80fd7e-e2c1-4dfb-b950-d7dc2f7a380d.jpg)
> > ![Screenshot_2023-02-20-21-14-09-051_com newin nplayer pro](https://user-images.githubusercontent.com/84889012/220118687-d86be4e5-2644-4b1f-9775-a181152a19a1.jpg)

把/删掉就行了

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
