### ISSUE TITLE
包路径里面有\就会报错

### ISSUE THREAD

**Issue by hulang1991** [eritpchy/aliyundrive-webdav#94]
昨天打开一个文件夹一直报错，然后看了下那个文件夹里面有个包名有个\修改之后正常

**Comment by eritpchy** [comment]
1

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.3.0.4.release.apk.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10908844/net.xdow.webdavaliyundriver.3.0.4.release.apk.zip)
试试
