### ISSUE TITLE
多实体安装 app，以便支持多账号登录

### ISSUE THREAD

**Issue by quartets** [eritpchy/aliyundrive-webdav#95]
我有 3 个阿里云盘账号，本来是在 windows 中开 3 个命令行窗口开支持的。这次阿里云盘升级 v3 接口后，支持得不完美，每 30 分钟断一次。

这个 android 解决方案很赞，装在 google box 里没有硬伤。但是一个问题，就是不能独立多次安装。

如果能把该 app 的系统名称改为 x1，x2，x3 就好了。如果编译前改一个字段就能实现吧？

**Comment by wenhelinlu** [comment]
> 我有 3 个阿里云盘账号，本来是在 windows 中开 3 个命令行窗口开支持的。这次阿里云盘升级 v3 接口后，支持得不完美，每 30 分钟断一次。
> 
> 这个 android 解决方案很赞，装在 google box 里没有硬伤。但是一个问题，就是不能独立多次安装。
> 
> 如果能把该 app 的系统名称改为 x1，x2，x3 就好了。如果编译前改一个字段就能实现吧？

使用多开类软件试试呢

**Comment by eritpchy** [comment]
建议使用docker版

**Comment by quartets** [comment]
能回答得具体点儿吗,哪个Android盒子能用的app?
