### ISSUE TITLE
失效了，设置好后连不上

### ISSUE THREAD

**Issue by SmarKid** [eritpchy/aliyundrive-webdav#98]
![微信图片_20230228230431](https://user-images.githubusercontent.com/49120793/221893595-18c697f2-b481-4882-b315-da12503adadc.jpg)
![微信图片_20230228230443](https://user-images.githubusercontent.com/49120793/221893606-1f2768b0-7e09-4558-ab37-66d2fe60e191.jpg)

**Comment by SmarKid** [comment]
es浏览器卡在增加服务器界面

**Comment by eritpchy** [comment]
[4.0.0](https://github.com/eritpchy/aliyundrive-webdav/releases/tag/4.0.0)
